//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenny_Lunch_Picker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favoriteRestaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public favoriteRestaurant()
        {
            this.users = new HashSet<user>();
        }
    
        public int restaurantId { get; set; }
        public string restaurantName { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string webAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
