//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenny_Lunch_Picker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class googleMapsApi
    {
        public int mapApiId { get; set; }
        public string mapKey { get; set; }
    }
}
