//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenny_Lunch_Picker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userId { get; set; }
        public Nullable<int> restaurantId { get; set; }
        public string userName { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime joinDate { get; set; }
        public string address { get; set; }
    
        public virtual favoriteRestaurant favoriteRestaurant { internal get; set; }
    }
}
